import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const grotesk = Hanken_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Henry | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={grotesk.className}>{children}</body>
    </html>
  );
}
